#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# get the commit message
commit_msg=$(cat "$1")

# Define ANSI color escape codes
RED='\033[0;31m'
NC='\033[0m' # No Color

# define regex of desired commit message pattern
regex="^(feat|fix|docs|style|refactor|perf|test|chore)(\([A-Za-z0-9_\-]+\))?: .+$"

# check if commit message follows commit regex and throw error if not follows
if ! echo "$commit_msg" | grep -qE "$regex"; then
  echo "${RED}ERR: Invalid commit message format.\nFIX: Please use 'type(scope): description' format.${NC}"
  exit 1
fi
